### ISSUE TITLE
完了したタスクがわかりやすいUIを作る

### ISSUE THREAD

**Issue by kensiiwasaki** [Ebi-web/react-room#23]

**Comment by masa5555** [comment]
追加で思ったのですが、完了状態を選択してフィルタリング表示できるセレクトボックスがあったらいいなと思いました。

- 全表示
- 未完了
- 完了
を選択するイメージです。

**Comment by kensiiwasaki** [comment]
@masa5555 
確かにですね！
フィルター機能はあるあるですもんね！

後似てますが、
階層が深くなりすぎた時に探すの大変なので
場合によっては検索機能的なのもあってもいいかもですね
